### ISSUE TITLE
Order API - Create Order

### ISSUE THREAD

**Issue by NikoIskra** [NikoIskra/order-service#4]
### AC

- Open Api Spec for this endpoint created
- Code is generated
- Endpoint logic is implemented
- `.http` docs is created
- logic is covered by unit tests (controller, services) for negative and positive scenarios

#### Request

Path: `api/v1/order`  
Method: `POST`  
Headers:
- `application/json`
- `X-ACCOUNT-ID: uuid`

Body:
- `providerId` - mandatory
- `comment` - optional, validation (length < 512)
- `clientContact`- mandatory, validation (length < 512)
- `deliveryAddress` - optional, validation (length < 512)
- `orderItemId` - mandatory
- `orderSubItemIds` - optional, array of
	- `id` mandatory
	- `quantity` - validate as > 0

#### Response
Status `CREATED`

- `BAD REQUEST` - data is invalid
- `CONFLICT` - unique constraint not met
- `NOT FOUND` - resource is missing
- `INTERNAL SERVER ERROR` - other errors

**Headers:**
- `Content-Type: application/json`
- `Location: /api/v1/order/{orderNumber}`

**Body:**

- `ok` - true if success, false in case of error
- `result`
    - `orderNumber`
    - `providerId`
    - `clientId`
    - `comment`
    - `totalPriceCents`
    - `clientContact`
    - `deliveryAddress`
    - `stage`
    - `status`
    - `details`
	    - `providerItemId`
	    - `quantity`
	    - `priceCents` 
	    - `subItems` array of
		    -  `providerSubItemId`
		    - `quantity`
		    - `priceCents` 
- `errorMessage` - short error description

### Implementation details

- `providerId` - validate account with `provider` role, `BAD REQUEST` if role is missing
- `clientId` - take value from `X-ACCOUNT-ID`  and validate account with `client` role, `BAD REQUEST` if role is missing
- `orderNumber` should be generated in following format `{M}{Y}-{DD}{RANDOM_TEXT}` example `X3-21A4BLS`
	- `M` - month code https://en.wikipedia.org/wiki/Delivery_month
	- `Y` - last digit in the year of order creation e.g. 202`3`
	- `DD` - day of month of order creation date. e.g. Tue, `21` Nov 2023
	- `RANDOM_TEXT` - 5 random uppercase chars or numbers
	-  validate that generated value is unique
-  `totalPriceCents` - needs to be calculated as sum of all item and sub items
- `stage` - `new`
- `status` - `in-progress`
- `orderItemId` and `orderSubItemIds` retrieve/validate data from Provider Service, return `NOT FOUND` if any is missing
- all insert operations need to be a part of the same Transaction

**Comment by vitalii-martynovskyi-gl** [comment]
#### Request

Path: `api/v1/order`  
Method: `POST`  
Headers:
- `application/json`
- `X-ACCOUNT-ID: uuid`

Body:
- `providerId` - mandatory
- `comment` - optional, validation (length < 512)
- `clientContact`- mandatory, validation (length < 512)
- `deliveryAddress` - optional, validation (length < 512)
- `orderItemId` - mandatory
- `orderSubItemIds` - array, optional

**Comment by vitalii-martynovskyi-gl** [comment]
#### Response
Status `CREATED`

- `BAD REQUEST` - data is invalid
- `CONFLICT` - unique constraint not met
- `NOT FOUND` - resource is missing
- `INTERNAL SERVER ERROR` - other errors

**Headers:**
- `Content-Type: application/json`
- `Location: /api/v1/order/{orderNumber}`

**Body:**

- `ok` - true if success, false in case of error
- `result`
    - `orderNumber`
    - `providerId`
    - `clientId`
    - `comment`
    - `totalPriceCents`
    - `clientContact`
    - `deliveryAddress`
    - `stage`
    - `status`
    - `details`
	    - `providerItemId`
	    - `quantity`
	    - `priceCents` 
	    - `subItems` array of
		    -  `providerSubItemId`
		    - `quantity`
		    - `priceCents` 
- `errorMessage` - short error description

**Comment by vitalii-martynovskyi-gl** [comment]
### Implementation details

- `providerId` - validate account with `provider` role, `BAD REQUEST` if role is missing
- `clientId` - take value from `X-ACCOUNT-ID`  and validate account with `client` role, `BAD REQUEST` if role is missing
- `orderNumber` should be generated in following format `{M}{Y}-{DD}{RANDOM_TEXT}` example `X3-21A4BLS`
	- `M` - month code https://en.wikipedia.org/wiki/Delivery_month
	- `Y` - last digit in the year of order creation e.g. 202`3`
	- `DD` - day of month of order creation date. e.g. Tue, `21` Nov 2023
	- `RANDOM_TEXT` - 5 random uppercase chars or numbers
	-  validate that generated value is unique
-  `totalPriceCents` - needs to be calculated as sum of all item and sub items
- `stage` - `new`
- `status` - `in-progress`
- `orderItemId` and `orderSubItemIds` retrieve/validate data from Provider Service, return `NOT FOUND` if any is missing
- all insert operations need to be a part of the same Transaction
